@echo off
REM Generated by Copilot under FIS AI Policy
REM ! Evalutation ONLY ! Developed using the Github Copilot Feature Testing org - NOT FOR PRODUCTION WORK

REM OMS_HOST: OMS TCP host used by MiniFIX scripts.
set OMS_HOST=127.0.0.1
REM OMS_PORT: OMS TCP port used by MiniFIX scripts.
set OMS_PORT=9876
REM SENDER_COMP_ID: FIX SenderCompID for MiniFIX client session.
set SENDER_COMP_ID=MINIFIX
REM TARGET_COMP_ID: FIX TargetCompID expected by OMS.
set TARGET_COMP_ID=EXCHANGE
REM MINIFIX: Full path to MiniFIX.exe daemon executable.
set MINIFIX=C:\Program Files (x86)\MiniFIX\MiniFIX.exe

reg query HKCU\Software\MiniFIX >nul 2>&1
if %errorlevel%==0 (
  reg add HKCU\Software\MiniFIX /v SenderCompId /t REG_SZ /d "4 %SENDER_COMP_ID%" /f >nul 2>&1
  reg add HKCU\Software\MiniFIX /v TargetCompId /t REG_SZ /d "4 %TARGET_COMP_ID%" /f >nul 2>&1
  reg add HKCU\Software\MiniFIX /v FixVersion /t REG_SZ /d "7 FIX.4.4" /f >nul 2>&1
)
