# Generated by Copilot under FIS AI Policy
# ! Evalutation ONLY ! Developed using the Github Copilot Feature Testing org - NOT FOR PRODUCTION WORK

param(
    [Parameter(Mandatory = $true)] [string]$ScriptFile,
    [Parameter(Mandatory = $true)] [string]$MiniFIX,
    [string]$OmsHost = '',
    [string]$OmsPort = '',
    [string]$SenderCompId = '',
    [string]$TargetCompId = '',
    [int]$TimeoutSeconds = 240,
    [int]$WaitSleepMs = 300,
    [switch]$Quiet = $false,
    [switch]$ReuseMiniFIX = $false
)

$ErrorActionPreference = 'Stop'

function Write-Info([string]$text) {
    if (-not $Quiet) {
        Write-Host $text -ForegroundColor DarkGray
    }
}

function Normalize-Tag([string]$tag) {
    if ($tag -match '^([^=]+)=(-?\d+(?:\.\d+)?)$') {
        $k = $Matches[1]
        $v = [decimal]$Matches[2]
        $vCanonical = $v.ToString('G29', [System.Globalization.CultureInfo]::InvariantCulture)
        return ('{0}={1}' -f $k, $vCanonical)
    }
    return $tag
}

function Test-TagPatternMatch {
    param(
        [string]$Message,
        [string[]]$Tags
    )

    foreach ($tag in $Tags) {
        $norm = Normalize-Tag $tag
        $rx = '(^|\|)' + [regex]::Escape($norm) + '(\||$)'
        if ($Message -notmatch $rx) {
            return $false
        }
    }
    return $true
}

function Test-MiniFixPipeReady {
    param([int]$TimeoutMs = 400)
    $pipe = $null
    try {
        $pipe = New-Object System.IO.Pipes.NamedPipeClientStream('.', 'minifix', [System.IO.Pipes.PipeDirection]::InOut)
        $pipe.Connect($TimeoutMs)
        return $true
    } catch {
        return $false
    } finally {
        if ($pipe) { $pipe.Dispose() }
    }
}

function Start-MiniFIXDaemon {
    param(
        [string]$MiniFixPath,
        [string]$WorkingDir
    )

    if (!(Test-Path $MiniFixPath)) {
        throw "MiniFIX executable not found: $MiniFixPath"
    }

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = 'cmd.exe'
    $psi.Arguments = '/c start /b "MiniFIX" "' + $MiniFixPath + '"'
    $psi.WorkingDirectory = $WorkingDir
    $psi.UseShellExecute = $false

    $starter = [System.Diagnostics.Process]::Start($psi)
    $starter.WaitForExit()
    $starter.Dispose()
    Start-Sleep -Milliseconds 300

    $mfProc = Get-Process MiniFIX -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $mfProc) {
        throw 'MiniFIX process did not start.'
    }

    $deadline = (Get-Date).AddSeconds(25)
    $ready = $false
    while ((Get-Date) -lt $deadline) {
        if (Test-MiniFixPipeReady -TimeoutMs 400) {
            $ready = $true
            break
        }
        Start-Sleep -Milliseconds 300
    }

    if (-not $ready) {
        Stop-Process -Id $mfProc.Id -Force -ErrorAction SilentlyContinue
        throw 'MiniFIX pipe did not become ready in 25 seconds.'
    }

    Start-Sleep -Milliseconds 300
    return $mfProc
}

if ($OmsHost -and $OmsPort) {
    $tcp = $null
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $ar = $tcp.BeginConnect($OmsHost, [int]$OmsPort, $null, $null)
        if (-not $ar.AsyncWaitHandle.WaitOne(3000)) {
            Write-Host "ERROR: OMS not reachable at $OmsHost`:$OmsPort" -ForegroundColor Red
            exit 3
        }
        $tcp.EndConnect($ar)
        Write-Info "  OMS reachable at $OmsHost`:$OmsPort"
    } catch {
        Write-Host "ERROR: OMS not reachable at $OmsHost`:$OmsPort" -ForegroundColor Red
        exit 3
    } finally {
        if ($tcp) { $tcp.Dispose() }
    }
}

$scriptPath = Resolve-Path $ScriptFile
$suiteDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$miniFixDir = Split-Path -Parent $MiniFIX
$scriptDir = Split-Path -Parent $scriptPath

$rawLines = Get-Content -Path $scriptPath
$scriptLines = @()
foreach ($line in $rawLines) {
    $line2 = $line
    if ($OmsHost) { $line2 = $line2.Replace('{{OMS_HOST}}', $OmsHost) }
    if ($OmsPort) { $line2 = $line2.Replace('{{OMS_PORT}}', $OmsPort) }
    if ($SenderCompId) { $line2 = $line2.Replace('{{SENDER_COMP_ID}}', $SenderCompId) }
    if ($TargetCompId) { $line2 = $line2.Replace('{{TARGET_COMP_ID}}', $TargetCompId) }
    $scriptLines += $line2
}
$scriptLines += ''
$scriptLines += 'Quit'

$resultsFile = $null
$verifyPatterns = @()
$verifyCountRules = @()
$pipeLines = New-Object 'System.Collections.Generic.List[string]'
$pastLogonWait = $false

$cleanupSymbols = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
foreach ($line in $scriptLines) {
    if ($line -match '\b55=([A-Za-z]+)\b') {
        [void]$cleanupSymbols.Add($Matches[1])
    }
    if ($line -match '^Execute:(.+):(\d+)\s*$') {
        $helper = Join-Path $scriptDir $Matches[1].Trim()
        if (Test-Path $helper) {
            Get-Content $helper | ForEach-Object {
                if ($_ -match '\b55=([A-Za-z]+)\b') {
                    [void]$cleanupSymbols.Add($Matches[1])
                }
            }
        }
    }
}

foreach ($line in $scriptLines) {
    if ($line -match '^\s*Quit\s*$') { continue }
    if ($line -match '^\s*#') { continue }

    if ($line -match '^Reset\s*$') {
        $pipeLines.Add('Reset')
        $pipeLines.Add('Sleep:1200')
        continue
    }

    if ($line -match '^Wait:35=A(?:\||\s*$)') {
        $pastLogonWait = $true
        $pipeLines.Add($line.Trim())
        continue
    }

    if ($line -match '^VerifyCount:(.+):(>=|<=|==|>|<)(\d+)\s*$') {
        $verifyCountRules += [PSCustomObject]@{
            Pattern = $Matches[1].Trim()
            Op      = $Matches[2]
            Count   = [int]$Matches[3]
        }
        continue
    }

    if ($line -match '^Save:(.+)$') {
        $saveTarget = $Matches[1].Trim()
        $resultsFile = Join-Path $suiteDir $saveTarget
        $pipeLines.Add(('Save:{0}' -f $resultsFile))
        continue
    }

    if ($pastLogonWait -and $line -match '^(Wait|Expect):(.+)$') {
        $verifyPatterns += $Matches[2].Trim()
        $pipeLines.Add("Sleep:$WaitSleepMs")
        continue
    }

    if ($line -match '^Execute:(.+):(\d+)\s*$') {
        $helperRel = $Matches[1].Trim()
        $repeat = [int]$Matches[2]
        $helperPath = Join-Path $scriptDir $helperRel

        if (!(Test-Path $helperPath)) {
            Write-Host "ERROR: Helper script not found: $helperPath" -ForegroundColor Red
            exit 1
        }

        $helperLines = Get-Content $helperPath | Where-Object { $_ -and ($_ -notmatch '^\s*#') }
        Write-Info ("Expanding helper {0} x {1}" -f $helperRel, $repeat)
        for ($i = 0; $i -lt $repeat; $i++) {
            foreach ($hl in $helperLines) {
                $pipeLines.Add($hl)
            }
        }
        continue
    }

    if ($line.Trim()) {
        $pipeLines.Add($line.Trim())
    }
}

if (-not $resultsFile) {
    $fallback = Join-Path $suiteDir ('results\' + [System.IO.Path]::GetFileNameWithoutExtension($scriptPath) + '_result.txt')
    $resultsFile = $fallback
    $pipeLines.Add("Save:$fallback")
}

if ($cleanupSymbols.Count -gt 0) {
    $disconnectIdx = -1
    for ($i = 0; $i -lt $pipeLines.Count; $i++) {
        if ($pipeLines[$i] -match '^Disconnect\s*$') {
            $disconnectIdx = $i
        }
    }

    if ($disconnectIdx -ge 0) {
        $cleanupBlock = New-Object 'System.Collections.Generic.List[string]'
        $cleanupBlock.Add('Sleep:200')
        $cleanupBlock.Add('# --- Post-test book cleanup ---')

        foreach ($sym in $cleanupSymbols) {
            $cleanupBlock.Add("Send:NewOrderSingle:11=`$UNIQUE|55=$sym|54=2|40=2|38=999999|44=0.01|59=0")
            $cleanupBlock.Add('Sleep:200')
            $cleanupBlock.Add("Send:OrderCancelRequest:11=`$UNIQUE|41=`$LASTUNIQUE|55=$sym|54=2|38=999999|60=`$TIMESTAMP")
            $cleanupBlock.Add('Sleep:200')
            $cleanupBlock.Add("Send:NewOrderSingle:11=`$UNIQUE|55=$sym|54=1|40=2|38=999999|44=999999.00|59=0")
            $cleanupBlock.Add('Sleep:200')
            $cleanupBlock.Add("Send:OrderCancelRequest:11=`$UNIQUE|41=`$LASTUNIQUE|55=$sym|54=1|38=999999|60=`$TIMESTAMP")
            $cleanupBlock.Add('Sleep:200')
        }

        $pipeLines.InsertRange($disconnectIdx, $cleanupBlock)
    }
}

$mfProc = Get-Process MiniFIX -ErrorAction SilentlyContinue | Select-Object -First 1
if ($ReuseMiniFIX -and $mfProc) {
    if (-not $mfProc.HasExited) {
        Write-Info ("Reusing MiniFIX (PID={0})" -f $mfProc.Id)
    } else {
        Write-Info 'MiniFIX exited - restarting...'
        Get-Process MiniFIX -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
        $mfProc = $null
    }
} elseif ($mfProc) {
    Write-Info 'Killing stale MiniFIX...'
    Get-Process MiniFIX -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
    $mfProc = $null
}

if (-not $mfProc) {
    try {
        $mfProc = Start-MiniFIXDaemon -MiniFixPath $MiniFIX -WorkingDir $miniFixDir
        Write-Info ("MiniFIX started (PID={0})" -f $mfProc.Id)
    } catch {
        Write-Host "ERROR: Failed to start MiniFIX: $($_.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

$markerFile = Join-Path $suiteDir 'results\_done_pipe.txt'
Remove-Item $resultsFile -Force -ErrorAction SilentlyContinue
Remove-Item $markerFile -Force -ErrorAction SilentlyContinue

$pipe = $null
$writer = $null
$connected = $false

for ($attempt = 1; $attempt -le 3; $attempt++) {
    try {
        $pipe = New-Object System.IO.Pipes.NamedPipeClientStream('.', 'minifix', [System.IO.Pipes.PipeDirection]::InOut)
        $pipe.Connect(3000)
        $connected = $true
        break
    } catch {
        if ($pipe) { $pipe.Dispose() }
        $pipe = $null

        if ($attempt -eq 1) {
            Write-Info 'Pipe connect attempt 1 failed, waiting...'
            Start-Sleep -Seconds 2
            continue
        }

        if ($attempt -eq 2) {
            Write-Info 'Pipe connect failed twice, restarting daemon...'
            Get-Process MiniFIX -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 2
            try {
                $mfProc = Start-MiniFIXDaemon -MiniFixPath $MiniFIX -WorkingDir $miniFixDir
                Write-Info ("MiniFIX restarted (PID={0})" -f $mfProc.Id)
            } catch {
                Write-Host "ERROR: Failed to restart MiniFIX: $($_.Exception.Message)" -ForegroundColor Red
                exit 1
            }
            continue
        }

        Write-Host 'ERROR: Pipe connect failed after 3 attempts.' -ForegroundColor Red
        exit 1
    }
}

if (-not $connected) {
    Write-Host 'ERROR: Could not connect to MiniFIX named pipe.' -ForegroundColor Red
    exit 1
}

try {
    $writer = New-Object System.IO.StreamWriter($pipe)
    $writer.AutoFlush = $true

    foreach ($line in $pipeLines) {
        if ($line -match '^\s*$') { continue }
        if ($line -match '^\s*#') { continue }
        $writer.WriteLine($line)
    }
    $writer.WriteLine('Save:results\_done_pipe.txt')

    if ($writer) { $writer.Dispose(); $writer = $null }
    if ($pipe) { $pipe.Dispose(); $pipe = $null }

    $autoTimeout = [Math]::Max($TimeoutSeconds, [Math]::Ceiling(($pipeLines.Count * 0.5) + 120))
    if ($autoTimeout -gt $TimeoutSeconds) {
        Write-Info ("Auto-scaled timeout: {0}s" -f $autoTimeout)
    }

    $deadline = (Get-Date).AddSeconds($autoTimeout)
    while ((Get-Date) -lt $deadline) {
        # Some MiniFIX runs do not emit the auxiliary marker reliably; the
        # scenario result file is the authoritative completion signal.
        if (Test-Path $resultsFile) {
            break
        }
        Start-Sleep -Milliseconds 100
    }
} catch {
    Write-Host "ERROR while writing to MiniFIX pipe: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
} finally {
    if ($writer) { $writer.Dispose() }
    if ($pipe) { $pipe.Dispose() }
}

if (!(Test-Path $resultsFile)) {
    Write-Host "FAIL: Result file was not created: $resultsFile" -ForegroundColor Red
    exit 2
}

$rawResult = Get-Content $resultsFile -Raw
$received = @()
Get-Content $resultsFile | ForEach-Object {
    if ($_ -like '> *') {
        $received += ($_.Substring(2).Trim())
    }
}

$logonIdx = -1
for ($i = 0; $i -lt $received.Count; $i++) {
    if ($logonIdx -lt 0 -and $received[$i] -match '(^|\|)35=A(\||$)') {
        $logonIdx = $i
    }
}
if ($logonIdx -ge 0) {
    $received = $received[$logonIdx..($received.Count - 1)]
}

$allPassed = $true
foreach ($pattern in $verifyPatterns) {
    $parts = $pattern.Split('|') | Where-Object { $_ -and $_.Trim() }
    $matched = $false
    foreach ($msg in $received) {
        if (Test-TagPatternMatch -Message $msg -Tags $parts) {
            $matched = $true
            break
        }
    }

    if (-not $matched) {
        $allPassed = $false
        Write-Host ("VERIFY FAIL: pattern [{0}] not matched" -f $pattern) -ForegroundColor Red
    }
}

foreach ($rule in $verifyCountRules) {
    $parts = $rule.Pattern.Split('|') | Where-Object { $_ -and $_.Trim() }
    $count = 0
    foreach ($msg in $received) {
        if (Test-TagPatternMatch -Message $msg -Tags $parts) {
            $count++
        }
    }

    $ok = $false
    switch ($rule.Op) {
        '>=' { $ok = $count -ge $rule.Count }
        '>'  { $ok = $count -gt $rule.Count }
        '<=' { $ok = $count -le $rule.Count }
        '<'  { $ok = $count -lt $rule.Count }
        '==' { $ok = $count -eq $rule.Count }
    }

    if ($ok) {
        Write-Info ("VERIFYCOUNT OK: [{0}] {1} {2} (actual={3})" -f $rule.Pattern, $rule.Op, $rule.Count, $count)
    } else {
        $allPassed = $false
        Write-Host ("VERIFYCOUNT FAIL: [{0}] {1} {2} (actual={3})" -f $rule.Pattern, $rule.Op, $rule.Count, $count) -ForegroundColor Red
    }
}

if ($verifyPatterns.Count -gt 0 -and $allPassed) {
    Write-Info ("All {0} verify pattern(s) matched" -f $verifyPatterns.Count)
}

$hasPassedKeyword = [regex]::IsMatch($rawResult, '\bPASSED\b')
$seqMismatch = ($received | Where-Object { $_ -match '58=.*MsgSeqNum' -or $_ -match '\|373=' } | Measure-Object).Count -gt 0

if ($allPassed -and $hasPassedKeyword) {
    exit 0
}

if (-not $allPassed -and -not $Quiet) {
    Write-Host 'Received messages:' -ForegroundColor Yellow
    $received | ForEach-Object { Write-Host ("  > {0}" -f $_) -ForegroundColor Yellow }
}

if ($seqMismatch) {
    Write-Host 'Sequence mismatch detected - exit 2' -ForegroundColor Yellow
    exit 2
}

exit 1
