@echo off
REM Generated by Copilot under FIS AI Policy
REM ! Evalutation ONLY ! Developed using the Github Copilot Feature Testing org - NOT FOR PRODUCTION WORK

setlocal enabledelayedexpansion

if "%~1"=="" (
  echo Usage: %~nx0 ^<path\to\test.txt^> [path\to\MiniFIX.exe]
  exit /b 1
)

call "%~dp0config.bat"

if not "%~2"=="" (
  set MINIFIX=%~2
)

set SCRIPT_FILE=%~1
if not exist "%SCRIPT_FILE%" (
  if exist "%~dp0%~1" (
    set SCRIPT_FILE=%~dp0%~1
  ) else (
    echo FAIL: script not found: %~1
    exit /b 1
  )
)

echo ==================================================
echo Running: %~nx1
echo OMS: %OMS_HOST%:%OMS_PORT%
echo SenderCompId: %SENDER_COMP_ID%
echo TargetCompId: %TARGET_COMP_ID%
echo ==================================================

powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0minifix_runner.ps1" ^
  -ScriptFile "%SCRIPT_FILE%" ^
  -MiniFIX "%MINIFIX%" ^
  -OmsHost "%OMS_HOST%" ^
  -OmsPort "%OMS_PORT%" ^
  -SenderCompId "%SENDER_COMP_ID%" ^
  -TargetCompId "%TARGET_COMP_ID%"
set RESULT=!errorlevel!

if "!RESULT!"=="3" (
  echo FAIL: %~nx1 ^(OMS not reachable at %OMS_HOST%:%OMS_PORT% - start the OMS then retry^)
  exit /b 1
)

if "!RESULT!"=="2" (
  echo Sequence mismatch detected - restarting MiniFIX and retrying...
  powershell -NoProfile -Command "Stop-Process -Name MiniFIX -Force -ErrorAction SilentlyContinue"
  timeout /t 3 /nobreak >nul

  powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0minifix_runner.ps1" ^
    -ScriptFile "%SCRIPT_FILE%" ^
    -MiniFIX "%MINIFIX%" ^
    -OmsHost "%OMS_HOST%" ^
    -OmsPort "%OMS_PORT%" ^
    -SenderCompId "%SENDER_COMP_ID%" ^
    -TargetCompId "%TARGET_COMP_ID%"
  set RESULT=!errorlevel!
)

if "!RESULT!"=="0" (
  echo PASS: %~nx1
  exit /b 0
)

echo FAIL: %~nx1
exit /b 1
