@echo off
REM Generated by Copilot under FIS AI Policy
REM ! Evalutation ONLY ! Developed using the Github Copilot Feature Testing org - NOT FOR PRODUCTION WORK

setlocal
set PS_EXE=powershell
where pwsh >nul 2>&1
if %errorlevel%==0 set PS_EXE=pwsh

set EXTRA_ARGS=
if not "%~1"=="" set EXTRA_ARGS=-MiniFIXPath "%~1"

%PS_EXE% -NoProfile -ExecutionPolicy Bypass -File "%~dp0run_all.ps1" %EXTRA_ARGS%
exit /b %errorlevel%
