# Generated by Copilot under FIS AI Policy
# ! Evalutation ONLY ! Developed using the Github Copilot Feature Testing org - NOT FOR PRODUCTION WORK

param(
    [string]$MiniFIXPath = '',
    [switch]$ShowDetail = $false
)

$ErrorActionPreference = 'Continue'

$suiteDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$configPath = Join-Path $suiteDir 'config.bat'
$runnerPath = Join-Path $suiteDir 'minifix_runner.ps1'
$markerPath = Join-Path $suiteDir 'results\_done_pipe.txt'
$miniFixDir = if ($MINIFIX) { Split-Path -Parent $MINIFIX } else { $suiteDir }

if (!(Test-Path $configPath)) {
    Write-Host "ERROR: Missing config.bat at $configPath" -ForegroundColor Red
    exit 1
}

Get-Content $configPath | ForEach-Object {
    if ($_ -match '^\s*set\s+(OMS_HOST|OMS_PORT|SENDER_COMP_ID|TARGET_COMP_ID|MINIFIX)=(.+)$') {
        Set-Variable -Name $Matches[1] -Value $Matches[2].Trim() -Scope Script
    }
}

if ($MiniFIXPath) { $MINIFIX = $MiniFIXPath }

$regKey = 'HKCU:\Software\MiniFIX'
if (Test-Path $regKey) {
    try {
        Set-ItemProperty -Path $regKey -Name SenderCompId -Value ("4 {0}" -f $SENDER_COMP_ID) -ErrorAction SilentlyContinue
        Set-ItemProperty -Path $regKey -Name TargetCompId -Value ("4 {0}" -f $TARGET_COMP_ID) -ErrorAction SilentlyContinue
        Set-ItemProperty -Path $regKey -Name FixVersion -Value '7 FIX.4.4' -ErrorAction SilentlyContinue
    } catch {
        Write-Host "WARN: Unable to preset MiniFIX registry keys: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

Get-Process MiniFIX -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

Write-Host '============================================================' -ForegroundColor Cyan
Write-Host 'OMS Test Suite - Running All Tests' -ForegroundColor Cyan
Write-Host ("OMS: {0}:{1} | SenderCompId: {2} | TargetCompId: {3}" -f $OMS_HOST, $OMS_PORT, $SENDER_COMP_ID, $TARGET_COMP_ID) -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan

$categoryDirs = Get-ChildItem -Path $suiteDir -Directory | Where-Object { $_.Name -match '^0\d_.*' } | Sort-Object Name
$cleanupPort = 8090
if ($env:OMS_REST_PORT -and $env:OMS_REST_PORT.Trim()) {
    $cleanupPort = [int]$env:OMS_REST_PORT.Trim()
}
$results = @()
$index = 1

foreach ($cat in $categoryDirs) {
    $tests = Get-ChildItem -Path $cat.FullName -File -Filter 'T*.txt' | Sort-Object Name
    foreach ($test in $tests) {
        Remove-Item $markerPath -Force -ErrorAction SilentlyContinue

        try {
            Invoke-RestMethod -Method Post -Uri ("http://{0}:{1}/api/orders/bulk-cancel" -f $OMS_HOST, $cleanupPort) -ContentType 'application/json' -Body '{"reason":"suite cleanup"}' -TimeoutSec 15 | Out-Null
        } catch {
            Write-Host ("WARN: cleanup failed before {0}: {1}" -f $test.Name, $_.Exception.Message) -ForegroundColor Yellow
        }

        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        & "$suiteDir\run_single.bat" $test.FullName
        $code = $LASTEXITCODE
        $sw.Stop()

        $status = if ($code -eq 0) { 'PASS' } else { 'FAIL' }
        $statusColor = if ($status -eq 'PASS') { 'Green' } else { 'Red' }
        Write-Host ("[{0}] {1} ({2:n1}s)" -f $status, $test.Name, $sw.Elapsed.TotalSeconds) -ForegroundColor $statusColor

        $results += [PSCustomObject]@{
            Num      = $index
            Category = $cat.Name
            Test     = $test.Name
            Status   = $status
            Time     = ('{0:n1}s' -f $sw.Elapsed.TotalSeconds)
        }

        $index++
        Start-Sleep -Milliseconds 200
    }
}

$total = $results.Count
$passed = ($results | Where-Object { $_.Status -eq 'PASS' }).Count
$failed = ($results | Where-Object { $_.Status -eq 'FAIL' }).Count

Write-Host ''
Write-Host ("Total: {0} | Passed: {1} | Failed: {2}" -f $total, $passed, $failed) -ForegroundColor Cyan
$results | Format-Table @{Label='#';Expression={$_.Num}}, Category, Test, @{Label='Result';Expression={$_.Status}}, Time -AutoSize

if ($failed -gt 0) {
    Write-Host ''
    Write-Host 'Failed tests:' -ForegroundColor Red
    $results | Where-Object { $_.Status -eq 'FAIL' } | ForEach-Object { Write-Host (" - {0}\{1}" -f $_.Category, $_.Test) -ForegroundColor Red }
}

Write-Host ''
Write-Host 'Tip: Run individual tests for detailed failure output: .\run_single.bat <path\to\test.txt>' -ForegroundColor Yellow

Get-Process MiniFIX -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

if ($failed -gt 0) { exit 1 }
exit 0
